# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: World Economy and International Relations Quantitative Analysis Guide
site_url: https://vgrigoryevsky.github.io/world-economy-and-international-relations-quantitative-analysis-guide
docs_dir: '../../docs/en'                           # Where to find the English markdown files
site_dir: '../../generated/en'                      # Where to put the English HTML files

repo_url: https://github.com/vgrigoryevsky/world-economy-and-international-relations-quantitative-analysis-guide

theme:
  name: material
  custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
  #  logo: assets/images/logo.svg                    # The logo is shared by all languages
  #  favicon: assets/images/favicon.ico              # The favicon is shared by all languages
  language: en
  font:
    h:
      PT Sans
    text:
      PT Sans
    code:
      Consolas
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Russian
      link: /ru/
      lang: ru

plugins:
  - search:
      lang:
        - en

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true